### ISSUE TITLE
[1.10.2] Crash on startup: Model bakery (Set bucket model)

### ISSUE THREAD

**Issue by ACGaming** [skyboy/MineFactoryReloaded#600]
- Forge 12.18.3.2316
- MineFactoryReloaded 2.9.0B1-217
- CoFHCore 4.1.4.7

Crash only occurs when I enable MFR in my modpack.
Crash report: https://paste.ubuntu.com/24879527

**EDIT:** Game loads fine if you set _B:MilkBucket_ to _false_, thus disabling the vanilla override.

**Comment by skyboy** [comment]
So far as we can determine isn't not MFR causing this crash; try disabling any other mods that alter the milk bucket to narrow down which one's interacting?

**Comment by P3pp3rF1y** [comment]
btw tried adding MFR to All the mods modpack and it worked correctly so you can likely rule out all the mods that are in that modpack as well as yours

**Comment by NicosaurusRex99** [comment]
@skyboy the second i removed MFR this error stopped for mee so it is an incompatibility somewhere

**Comment by Elit3WolfPack** [comment]
Looks like there is an incompatibility with the milk changes from forestry, you have to disable the changes from either MFR or forestry and it will load, at least this worked in my case.

**Comment by NicosaurusRex99** [comment]
Not just forestry its something else too.

**Comment by NicosaurusRex99** [comment]
Pams harvestCraft will also cause this

**Comment by NicosaurusRex99** [comment]
something about this
https://pastebin.com/XrpdBN4y

**Comment by accessdenied0** [comment]
I can proof @P3pp3rF1y statement as false.
The "All the Mods (1.10.2) Modpack crashes like "Age of Engineering" (modified with MFR and cofh only). It would be strange if Forestry would be a possible compat cause and on the other hand not.

Strangely enough I got my own modpack running one time. Maybe a coincidence? 

Anyway if you remove Forestry (and all components for Forestry of course) it is running perfectly. I do not see any issue with Pam's Harvestcraft here cause it seem to run with it just fine.

The only cause for this issue so far I can confirm is Forestry.

**Comment by P3pp3rF1y** [comment]
Interesting that must be different settings or different version of forestry in my version of all the mods.

**Comment by P3pp3rF1y** [comment]
Could you actually share the forestry config that you have? This made me realize that we use forestry in dev environment all along and even when I updated to the latest version I still am unable to recreate this issue.

**Comment by accessdenied0** [comment]
I never changed anything on the "All The Mods" pack and It is on the newest version. The version of Forestry the pack is using is 1.10.2-5.2.17.376. The difference must be on your side.

**Comment by accessdenied0** [comment]
I tested the solution of @Elit3WolfPack and disabled the option of the "MilkBucket" override from true to false:
  `VanillaOverride {
        # If true, replaces the vanilla milk bucket so milk can be placed in the world.
        B:MilkBucket=false
   }`
at least in my privat pack it is now loading up just fine. It seem it is just that after all.

**Comment by P3pp3rF1y** [comment]
One last question, are you running into this issue on server? Because I tried redownloading latest all the mods version and only added MFR to it and it still didn't crash for me, but I am testing all of this in single player. Potentially on server the mod load order may be different and that could cause the issue you're seeing.

**Comment by skyboy** [comment]
Additionally, I'd like to see if this version resolves the problem:
[MineFactoryReloaded-[1.10.2]2.9.0B1-CUSTOM_BUILD.jar.zip](https://github.com/skyboy/MineFactoryReloaded/files/1083280/MineFactoryReloaded-.1.10.2.2.9.0B1-CUSTOM_BUILD.jar.zip)

Just note this isn't a release and is just for testing this issue; I'll convert it into a proper fix if it does work.

**Comment by accessdenied0** [comment]
@P3pp3rF1y singleplayer. MultiMC as well the normal Minecraft launcher. Java version is the newest. All in optimal conditions. And the issue persists.

@skyboy I tried your version and it loaded up. The world I tested it on works, too. This seem to fix it.
I have to notice: The world/pack I tested this on has no Pam's Harvestcraft. I might do testing this later.

**Comment by skyboy** [comment]
Resolved by 1e2b55ad087830c0c073c8a40b296e3c0fd20983

**Comment by DarkBreaker09** [comment]
I am still having the Crash on Startup problem.
I did try your Configs posted here.
I did try the Custom Build jar.
I cant say what it is. If i am just to stupid to get it work or if i dont see the real problem.
Anyways i am still geting the Crashes and hope you guys can help me.
Here is my Crash log : 
https://pastebin.com/h8K5pgnx

**Comment by Yorick1234** [comment]
Well, for me, after three days of trials and error, it seemed it was Sanguimancy that was the issue. Deleted that, it worked. Even with no forestry milk disabled. Which isn't B:milkbuckets btw, couldn't find that option, just B:milk and found twice (config\forestry\fluids.cfg). Hope this may help someone.
