### ISSUE TITLE
Grinder causes Crash / ExecutionException

### ISSUE THREAD

**Issue by wilkemeyer** [skyboy/MineFactoryReloaded#608]
Placing a Grinder causes Crash (see Below)

Happens in Singleplayer as well as Multiplayer.

This Exception seems to be caused by code of CoFHCore, but as corresponding code was provided by MFR only in previous releases (removed in MFR with b01f5286afe62dbf2f1b8d5df8e90bf96d9f157b) and moved to CoFHCore in March i thought this would be the best place for reporting the Issue.

**Steps to Reproduce**
1. Install Plain Minecraft/Forge
2. Install CoFHCore, CodeChickenLib, MinefactoryReloaded
3. Create a new Game,
4. Place the Grinder (or Slaughterhause as they both use the custom WorldServer Proxy)
5. See the exception / crash

**Installed (Mod) Versions**
- Forge: 12.18.3.2316
- CodeChickenLib: 1.10.2-2.5.9.267
- CoFHCore: 1.10.2-4.1.6.10
- MinefactoryReloaded: [1.10.2]2.9.0B1-220  (also tested custom build of rev. be06fa0b83710f2a7be9ca4665f14270cca99df1)

**Exception/Dump**
```
Error executing task
java.util.concurrent.ExecutionException: java.lang.VerifyError: Bad access to protected data in invokevirtual
Exception Details:
  Location:
    cofh/asmhooks/world/WorldServerProxy.func_72970_h()Lnet/minecraft/world/chunk/IChunkProvider; @4: invokevirtual
  Reason:
    Type 'net/minecraft/world/WorldServer' (current frame, stack[0]) is not assignable to 'cofh/asmhooks/world/WorldServerProxy'
  Current Frame:
    bci: @4
    flags: { }
    locals: { 'cofh/asmhooks/world/WorldServerProxy' }
    stack: { 'net/minecraft/world/WorldServer' }
  Bytecode:
    0x0000000: 2ab4 003a b603 bfb0                    

	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149) [bzl.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.VerifyError: Bad access to protected data in invokevirtual
Exception Details:
  Location:
    cofh/asmhooks/world/WorldServerProxy.func_72970_h()Lnet/minecraft/world/chunk/IChunkProvider; @4: invokevirtual
  Reason:
    Type 'net/minecraft/world/WorldServer' (current frame, stack[0]) is not assignable to 'cofh/asmhooks/world/WorldServerProxy'
  Current Frame:
    bci: @4
    flags: { }
    locals: { 'cofh/asmhooks/world/WorldServerProxy' }
    stack: { 'net/minecraft/world/WorldServer' }
  Bytecode:
    0x0000000: 2ab4 003a b603 bfb0                    

	at powercrystals.minefactoryreloaded.tile.machine.TileEntityGrinder.func_145834_a(TileEntityGrinder.java:80) ~[TileEntityGrinder.class:?]
	at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:809) ~[asv.class:?]
	at net.minecraft.world.World.func_175690_a(World.java:2461) ~[aid.class:?]
	at net.minecraft.world.chunk.Chunk.func_177424_a(Chunk.java:785) ~[asv.class:?]
	at net.minecraft.world.World.func_175625_s(World.java:2402) ~[aid.class:?]
	at powercrystals.minefactoryreloaded.block.BlockFactoryMachine.getLightOpacity(BlockFactoryMachine.java:109) ~[BlockFactoryMachine.class:?]
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.getLightOpacity(BlockStateContainer.java:475) ~[art$a.class:?]
	at net.minecraft.world.chunk.Chunk.func_177436_a(Chunk.java:589) ~[asv.class:?]
	at net.minecraft.world.World.func_180501_a(World.java:331) ~[aid.class:?]
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:165) ~[acl.class:?]
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54) ~[acl.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:780) ~[ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:145) ~[adz.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:483) ~[lv.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:679) ~[me.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) ~[jj.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) ~[jj.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[fl$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:45) ~[h.class:?]
	... 5 more```

**Comment by skyboy** [comment]
This will be resolved in the next release of core for 1.10. I'll close this issue once that happens.

**Comment by skyboy** [comment]
Fixed by CoFHCore 4.1.7.11

**Comment by DeadSix27** [comment]
I just tried this with CoFHCore-1.10.2-4.1.7.11-universal and it still does the same thing tho.
(I wrote this after I opened the dupe issue report)

Versions I run: "CoFHCore-1.10.2-4.1.7.11-universal.jar" and "MineFactoryReloaded-[1.10.2]2.9.0B1-221.jar"

**Comment by MUSE-iC** [comment]
Yup this issue is still present for me as well.
I tried the latest ver. of forge, recommended ver. of forge, and the one my server uses (2297). 
As I wasnt sure if that might have an effect. I also tried both of the available versions of MFR (220 & 221),

They all crashed with the same error.
[crash-2017-06-23_06.31.08-server.txt](https://github.com/skyboy/MineFactoryReloaded/files/1097631/crash-2017-06-23_06.31.08-server.txt)
[crash-2017-06-23_06.23.58-server.txt](https://github.com/skyboy/MineFactoryReloaded/files/1097630/crash-2017-06-23_06.23.58-server.txt)
[crash-2017-06-23_06.20.58-server.txt](https://github.com/skyboy/MineFactoryReloaded/files/1097636/crash-2017-06-23_06.20.58-server.txt)
[crash-2017-06-23_06.25.21-server.txt](https://github.com/skyboy/MineFactoryReloaded/files/1097635/crash-2017-06-23_06.25.21-server.txt)
[crash-2017-06-23_06.22.32-server.txt](https://github.com/skyboy/MineFactoryReloaded/files/1097638/crash-2017-06-23_06.22.32-server.txt)
[crash-2017-06-23_06.26.08-server.txt](https://github.com/skyboy/MineFactoryReloaded/files/1097637/crash-2017-06-23_06.26.08-server.txt)
