### ISSUE TITLE
Crash on loading most MFR things (with TE or EnderIO)

### ISSUE THREAD

**Issue by JSJBDEV** [skyboy/MineFactoryReloaded#647]
Description: Rendering item

java.lang.IllegalStateException: Already building!
	at net.minecraft.client.renderer.VertexBuffer.func_181668_a(VertexBuffer.java:187)
	at codechicken.lib.render.buffer.BakingVertexBuffer.func_181668_a(BakingVertexBuffer.java:55)
	at cofh.thermalexpansion.render.RenderMachine.bakeItemQuads(RenderMachine.java:104)
	at codechicken.lib.model.blockbakery.BlockBakery.generateItemModel(BlockBakery.java:185)
	at codechicken.lib.model.blockbakery.BlockBakery.getCachedItemModel(BlockBakery.java:160)
	at codechicken.lib.model.blockbakery.CCBakeryModel$1.handleItemState(CCBakeryModel.java:63)
	at net.minecraft.client.renderer.RenderItem.func_184393_a(RenderItem.java:249)
	at codechicken.lib.render.item.CCRenderItem.func_184393_a(CCRenderItem.java:297)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:228)
	at codechicken.lib.render.item.CCRenderItem.func_180450_b(CCRenderItem.java:220)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:867)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:703)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:76)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:591)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

this does not happen when MFR is removed and I am told only happens when Thermal Expansion or EnderIO are installed. it crashes for me on loading the MFR tab in creative and appears to crash when fluids are involved. I can send the entire crash log if you would like

**Comment by piedpipr314** [comment]
@skyboy I've been working pretty diligently on this one.  Two different crash logs for basically what seems to be the same thing.  If you need more info, check the referenced issue, please.  It seems to happen only in a specific scenario.

**Comment by P3pp3rF1y** [comment]
Why do you feel like this is crash caused by MFR when the only thing that the crash references is TE? 
And there actually are no fluids or fluid related things in MFR creative tab. 

Just to be sure I went through MFR's vertex code and made sure that we're always finishing drawing and I can't see any issue there. So I find it hard to believe that MFR would be directly causing this.

**Comment by piedpipr314** [comment]
Because if you remove MFR with the same exact mods otherwise, it doesn't crash.

**Comment by P3pp3rF1y** [comment]
Are there any other exceptions that you could see in the log? 
Because I don't see us not finishing drawing even in case an exception happens when it's trying to draw something. So if there would be an exception thrown during drawing by MFR (and thus causing this issue later on) it would be logged by forge or CCL and would clearly point to MFR code. You will find this in the log folder not in the crash one.

**Comment by P3pp3rF1y** [comment]
Also having a full crash log would help to see which other mods are in the pack and possibly being able to recreate the issue as I am unable to at all.

**Comment by P3pp3rF1y** [comment]
Just spoke to covers1624, this was caused by journeymap interacting with mods in a not nice way. He has pushed a change to CodeChickenLib to prevent this from happening. 
It will still cause issues (different than this, but the original that really causes this) that will get logged in the log, but will not crash the game.

**Comment by piedpipr314** [comment]
Oh, that's interesting.  I didn't even think to look there.  I duplicated this crash via a recipe lookup for fluid, and thought it was a fluidhandler.  That is very strange.

**Comment by piedpipr314** [comment]
For anyone else's future reference, I kinda knew this but had forgotten.  The latest log for Forge is under the instance folder, under /logs/latest.txt   Thanks @P3pp3rF1y for your help!

**Comment by piedpipr314** [comment]
Can confirm, downgrading to Journeymap 1.10.2-5.4.7 solves all issues associated with this crash.  It would have taken me a very long time to diagnose this on my own.

**Comment by JSJBDEV** [comment]
so after all this time we should've been complaining at techbrew xD. This is stil pretty confusing why these things break the way they do, but thanks @p3pp3rF1y for getting this sorted for us. It seems to be highly unusual circumstances (especially if we effectively had to go through 3 mods)

**Comment by JSJBDEV** [comment]
I shall put my log up here when I get the chance anyway

**Comment by piedpipr314** [comment]
Just as a note, as @P3pp3rF1y says, even after you downgrade, it still does show in the log and not crash.  It doesn't look like codechickenlib will be fixed for 1.10 though.  https://github.com/TheCBProject/CodeChickenLib/issues/61

**Comment by P3pp3rF1y** [comment]
it already is fixed in 1.10 CCL as of 9 hours ago https://minecraft.curseforge.com/projects/codechicken-lib-1-8/files/2447314

**Comment by piedpipr314** [comment]
Hrm, that's what version I'm using, and it still crashes with the beta Journeymap.  Is this a CodechickenLib problem then?

**Comment by P3pp3rF1y** [comment]
what you reference there is actually a different issue from what was reported here (at least per log over there). So if that's the one that you're getting you will need to follow up on CCL issue tracker.

**Comment by piedpipr314** [comment]
Okay, thanks!  I'll get a crash report and log for covers1624, and see what they say.

**Comment by piedpipr314** [comment]
"No, this is the phantom mfr milk bucket crash."

**Comment by piedpipr314** [comment]
same as https://github.com/skyboy/MineFactoryReloaded/issues/646 ?

**Comment by P3pp3rF1y** [comment]
Yes that log is for the phantom bucket issue so let's track that in the correct issue. #646 is ok for that. Let us know over there if downgrading journeymap really fixes the issue. I kind of doubt as bucket is issue is very different from this one, but we're looking for any kind of lead we can get on that.

**Comment by piedpipr314** [comment]
I've gotten both crashes, the one referenced above by @JSJBDEV as well on the same instance if the pack loads, I think they're related.

**Comment by JSJBDEV** [comment]
I'm not at acro outer now but if I remember correctly you can turn MFR milk bucket off in its config (powercrystals/minefactory/config) someone check if that helps

**Comment by JSJBDEV** [comment]
"At a computer

**Comment by P3pp3rF1y** [comment]
it does as was discussed in that other issue

**Comment by JSJBDEV** [comment]
Sorry, so then to fix this temporarily if indeed this is the main problem here couldn't one of us (I can if I have time) just register a Seperate version of MFRs milk implementation?

**Comment by skyboy** [comment]
This specific crash, as what the original post shows, is caused by journeymap and its logic to get the color of a block.

The milk bucket crash is unrelated, and is an interplay with some other mod, or load order or something. We don't really know, and the crash's inconsistency isn't helping to track down where or why it's going wrong.

<hr/>

Resolved by https://github.com/TheCBProject/CodeChickenLib/commit/cbadb4d8161b5c125861f4b55bdeebd4209a8e51
